### ISSUE TITLE
Implement DocView page

### ISSUE THREAD

**Issue by OmriLevyTau** [OmriLevyTau/webui#2]
Implement DocView page:
1. a generic page which can display word document
2. edit DocView.jsx file
3. Create relevant tests!

Notes:
component can get any path of local word file, and display it in page.
It should be read only, and should have a navbar above with document name and other metadata, as specified in the design spec.

relevant resources:
most for sure we need to se other open-source project for that. For example:
1. https://medium.com/@NTulswani/introducing-redocx-d1edff227ab2
2. https://github.com/Alcumus/react-doc-viewer
3. https://blog.devgenius.io/how-to-use-react-file-previewer-da7427ec1715

Can probably find better open-source for this, just examples..

**Comment by uriaviad** [comment]
question: is docx or pdf more natural to upload? 

1. upload only docx, convert to pdf in backend, show pdf with iframe/react-pdf
 - proof of viability: (1) show that we can convert docx to pdf in backend (gottenberg?)
 - (2) show that we can read the content of a docx file

2. upload pdf, show pdf with iframe/react
 - proof of viability: show that we can read raw content of a pdf file (ocr?)

3. upload txt or json
 -proof of viability: clearly viable 

4: both 1 and 2 (and 3?)
