### ISSUE TITLE
Explore authentication and user-context methods

### ISSUE THREAD

**Issue by OmriLevyTau** [OmriLevyTau/webui#7]
Explore authentication methods (using **firebase**), should answer the following questions:
1. Is authentication done through frontend only or backend should be involved?
2. How to store user session (remember the user that is logged in) and load a context specified for her/him?
3. Create a simple firebase login component implementing the previous conclusions.

Then, assuming a user is logged-in:
1. How can we display user-specified data only?
2. How to manage app context?

relevant resources:
1. https://abvijaykumar.medium.com/chapter-7-book-library-react-js-front-end-with-firebase-authentication-deployed-on-k8s-with-c4d150ae8d1b
2. https://www.youtube.com/watch?v=6kgitEWTxac

**Comment by idanisraeli** [comment]
what we need to do:

1. we need to make the sign up button change to logout button while signed in
2. useeffect is called 4 times (printing 4 times)
3. a little delay - showing protected route and then go to sign up page
4. tests
